CREATE TABLE [dbo].[Address]
(
	[AddressId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY CONSTRAINT DF_Address_AddressId DEFAULT NEWID(),
	[Description] NVARCHAR(255) NOT NULL,
	[Line1] NVARCHAR(100) NULL,
	[Line2] NVARCHAR(100) NULL,
	[City] NVARCHAR(100) NOT NULL,
	[State] NVARCHAR(2) NOT NULL,
	[ZipCode] NVARCHAR(5) NULL,
	[Latitude] BIGINT NULL,
	[Longitude] BIGINT NULL,
	[CreatedBy] NVARCHAR(100) NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[ModifiedBy] NVARCHAR(100) NULL,
	[ModifiedDate] DATETIME NULL
)
