CREATE TABLE [dbo].[Family]
(
	[FamilyId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[LastName] NVARCHAR(100) NOT NULL,
	[PhotoLocation] NVARCHAR(255) NULL,
	[Attending] BIT NOT NULL CONSTRAINT DF_Family_Attending DEFAULT 0,
	[ReceivingAlerts] BIT NOT NULL CONSTRAINT DF_Family_ReceivingAlerts DEFAULT 1,
	[AddressId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_Family_AddressId FOREIGN KEY REFERENCES [dbo].[Address]([AddressId]),
	[CreatedBy] NVARCHAR(100) NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[ModifiedBy] NVARCHAR(100) NULL,
	[ModifiedDate] DATETIME NULL
)
