CREATE TABLE [dbo].[Reunion]
(
	[ReunionId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY CONSTRAINT PK_Reunion_ReunionId DEFAULT NEWID(),
	[Name] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(4000) NULL,
	[StartDate] DATE NULL,
	[EndDate] DATE NULL,
	[AddressId] UNIQUEIDENTIFIER NULL CONSTRAINT FK_Reunion_AddressId FOREIGN KEY REFERENCES [dbo].[Address](AddressId),
	[CreatedBy] NVARCHAR(100) NOT NULL CONSTRAINT DF_Reunion_CreatedBy DEFAULT SUSER_SNAME(),
	[CreatedDate] DATETIME NOT NULL CONSTRAINT DF_Reunion_CreatedDate DEFAULT SYSDATETIME(),
	[ModifiedBy] NVARCHAR(100) NULL,
	[ModifiedDate] DATETIME NULL, 
    [IsActive] BIT NOT NULL DEFAULT 1
)
