CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY CONSTRAINT DF_User_Id DEFAULT NEWID(),
	[UserId] NVARCHAR(100) NOT NULL,
	[FirstName] NVARCHAR(100) NULL,
	[LastName] NVARCHAR(100) NULL,
	[Email] NVARCHAR(255) NOT NULL,
	[PhoneNumber] NVARCHAR(15) NULL,
	[CreatedBy] NVARCHAR(100) NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[ModifiedBy] NVARCHAR(100) NULL,
	[ModifiedDate] DATETIME NULL
)
