CREATE TABLE [dbo].[User]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY CONSTRAINT DF_User_UserId DEFAULT NEWID(),
	--[AppUserId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_User_AppUserId REFERENCES [dbo].[AspNetUsers]([Id]),
	[Email] NVARCHAR(255) NOT NULL,
	[PhoneNumber] NVARCHAR(15) NULL,
	[CreatedBy] NVARCHAR(100) NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
	[ModifiedBy] NVARCHAR(100) NULL,
	[ModifiedDate] DATETIME NULL
)
